AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Lambda-pipline for photo album
Resources:
  Lambda1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf1
      Description: 'Photo index insertion'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::471112677017:role/IndexPhotosLambdaExecutionRole'
      Environment:
        Variables:
          REGION: us-east-1

  Lambda2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./lf2
      Description: 'Photo search'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::471112677017:role/SearchPhotosLambdaExecutionRole'
      Environment:
        Variables:
          REGION: us-east-1